// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	My_First_Dialogue = 0,
	First_Band_is_up = 1,
	Second_Band_is_up = 2,
	no_more_food = 3,
	People_are_getting_sick = 4,
	People_are_loving_the_shirts = 5,
	bathroom = 6,
	Last_band = 7,
	Goodbye = 8,
	Posters = 9,
	Marketing = 10,
	shows_over = 11,
}
